### ISSUE TITLE
Change Readme File Of App

### ISSUE THREAD

**Issue by mustafaazad03** [Mustafa-Azad025/Real-Estate-app#3]
Please Add The Proper Info Of App

**Comment by anuragK-24** [comment]
can i do this task?

**Comment by Mohit-Aasirwal** [comment]
assign me!

**Comment by mustafaazad03** [comment]
sorry @hfr58gb , I will raise another issue you can request on that

**Comment by anuragK-24** [comment]
sure @Mustafa-Azad025
