### ISSUE TITLE
Adding Footer

### ISSUE THREAD

**Issue by mustafaazad03** [Mustafa-Azad025/Real-Estate-app#5]
Hi Folks,
I Want a Footer Having 
-Four Column 
-Having Professional Look
-Contact Form Want

and If You Like My Project Then You Can Give Me Star And Follow For More Such Issues .

**Comment by anuragK-24** [comment]
can u assign this task to me ?

**Comment by G0V1NDK** [comment]
Assign me this issue. I can do this task.

**Comment by mustafaazad03** [comment]
Hey @hfr58gb ,
I have assign task to you go ahead

**Comment by mustafaazad03** [comment]
> Assign me this issue. I can do this task.

Hey @G0V1NDK ,
You Can Also Go ahead If i find anything unique and creative i will add that to @hfr58gb merged file and you also get benifit of hacktoberfest.

**Comment by anuragK-24** [comment]
sorry for late PR, please check the PR
task done 
Thanks @Mustafa-Azad025

**Comment by mustafaazad03** [comment]
Can you provide screen shot ??

**Comment by anuragK-24** [comment]
Here it is
![image](https://user-images.githubusercontent.com/88237080/194341667-af6c874f-b6f5-4989-a22b-85ae5093eed1.png)

**Comment by mustafaazad03** [comment]
Ok Nice I will merge this
